<?php
/**
 * Declared variable
 * @var ak
 * @var actual
 * @var liga
 * @var baseSp
 */
$ak     = '73fee4973791892d5cd9fa0f8411da51';
$actual = '5';
$liga  = '1312';
$baseSp   = 'https://api.wh.sportingpulseinternational.com';
define("ak", $ak);
define("actual",$actual);  // liga
define("liga",$liga);  // conmetitions
define("baseSp", $baseSp);
$query= baseSp . '/v1/basketball/competitions/' . liga . '/standings?latest=1&format=json&limit=50000&ak='. ak .'';
/**
 * Implementation of hook_menu().
 */
function ligadtv_menu(){
  $menu = array();
  $menu['admin/config/video-home'] = array(
    'title'            => t('Video Home'),
    'description'      => t('Form config video home'),
    'page callback'    => '_video_home_config',
    'access arguments' => array('access content'),
    'file'             => 'ligadtv.pages.inc',
    'type'             => MENU_CALLBACK,
  );
  return $menu;
}


/**
 * Implementation of hook_block_info().
**/
function ligadtv_block_info() {
  $blocks = array();
  $blocks['slidorion'] = array(
    'info'  => t('slidorion home'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    );
  $blocks['table_positions'] = array(
    'info'  => t('Table positions'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['next_macth'] = array(
    'info'  => t('Next macth'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['latest_results'] = array(
    'info'  => t('Latest result'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['fb_widget'] = array(
    'info'  => t('Facebook widget'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['tw_widget'] = array(
    'info'  => t('Twitter widget'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['video_home'] = array(
    'info'  => t('Video Home'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['transmition'] = array(
    'info'  => t('Transmition'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['points_media'] = array(
    'info'  => t('Points media'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['half_rebounds'] = array(
    'info'  => t('Half rebounds'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['media_assistance'] = array(
    'info'  => t('MEDIA ASSISTANCE'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  $blocks['sponsors_home'] = array(
    'info'  => t('Sponsors Home'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}
/**
 * Implementation of hook_block_view().
 */
/**
 * Implementation of hook_block_view().
 * @param  string $delta [description]
 * @return [type]        [description]
 */
function ligadtv_block_view($delta = '') {
    $block = array();
    switch ($delta) {
      case 'slidorion':
        $block['title'] = '<none>';
        $items    = _get_content_custom('article', 6);
        //drupal_add_library('ligadtv', 'slidorion-master');
        drupal_add_js(drupal_get_path('module', 'ligadtv') . '/libraries/slidorion-master/js/jquery.easing.js' , 'file');
        drupal_add_js(drupal_get_path('module', 'ligadtv') . '/libraries/slidorion-master/dist/jquery.slidorion.min.js' , 'file');
        drupal_add_js(drupal_get_path('module', 'ligadtv') . '/js/ligadtv.js', 'file');
        drupal_add_css(drupal_get_path('module', 'ligadtv') . '/libraries/slidorion-master/css/slidorion.css', 'file');
        $block['content'] =array(
                  '#theme' => 'slidorion',
                  '#items' => array($items),
                  );
      break;
      case 'table_positions':
        $block['title'] = '<none>';
        $maxRound = 0;
        $data    = getStanding();
        foreach ($data as $key => $value) {
                    if ($value['roundNumber'] > $maxRound) {
                        $maxRound = $value['roundNumber'];
                    }
                }
           $block['content'] =array(
                  '#theme' => 'table_positions',
                  '#items' => array($data, $maxRound),
                  );
      break;
      case 'next_macth':
        $data = getCal();
        $block['content'] =array(
                  '#theme' => 'next_macth',
                  '#items' => array($data),
                  );
      break;
      case 'latest_results':
        $data = getRes();
        $block['content'] =array(
                  '#theme' => 'latest_result',
                  '#items' => array($data),
                  );
      break;
      case 'fb_widget':
        $block['content'] = array(
                  '#theme' => 'fb',
                  '#items' => array(),
          );
      break;
      case 'tw_widget':
        $block['content'] = array(
                  '#theme' => 'twitter',
                  '#items' => array(),
          );
      break;
      case 'video_home':
        $block['content'] = array(
                  '#theme' => 'video_home',
                  '#items' => array(),
          );
      break;
      case 'transmition':
        $transmition = transmition();
        $block['content'] = array(
                  '#theme' => 'transmition',
                  '#items' => array("transmition"=> $transmition),
        );
      break;
      case 'points_media':
        $points = getLeaderPoints();
        $items = drawLeader($points,$players,$teams,'sPointsAverage','MP');
        $block['content'] = array(
                          '#theme' => 'points_media',
                          '#items' => $items,
                );
      break;
      case 'half_rebounds':
        $points= getLeaderPointsRebotes();
        $items =drawLeader($points,$players,$teams,'sReboundsTotalAverage','REBM');
        $block['content'] = array(
                          '#theme' => 'half_rebounds',
                          '#items' => $items,
                );
      break;
      case 'media_assistance':
        $points= getLeaderMediaAsistencias2();
        $items =drawLeader($points,$players,$teams,'sAssistsAverage','MAS');
        $block['content'] = array(
                          '#theme' => 'media_assistance',
                          '#items' => $items,
                );
      break;
      case 'sponsors_home':
        $block['content'] = array(
                          '#theme' => 'sponsors_home',
                          '#items' => array(),
                );
      break;
    }
  return $block;
}

/**
 * Implementation of hook_theme().
*/
function ligadtv_theme(){
  return array(
  'slidorion' => array(
            'template' => 'theme/slidorion',
            'variables' => array(
                'items' => array(),
          )
        ),
  'table_positions' => array(
            'template' => 'theme/table_positions',
            'variables' => array(
                'items' => array(),
          )
        ),
  'next_macth' => array(
            'template' => 'theme/next_macth',
            'variables' => array(
                'items' => array(),
          )
        ),
  'latest_result' => array(
            'template' => 'theme/latest_result',
            'variables' => array(
                'items' => array(),
          )
        ),
  'fb'            => array(
            'template'  => 'theme/fb',
            'variables' => array(
                'items' => array(),
              ),
        ),
  'twitter'       => array(
            'template'  => 'theme/twitter',
            'variables' => array(
                'items' => array(),
              ),
        ),
  'home_form'     => array(
            'template'  => 'theme/home_form',
            'variables' => array(
                'items' => array(),
              ),
        ),
  'video_home'     => array(
            'template'  => 'theme/video_home',
            'variables' => array(
                'items' => array(),
              ),
        ),
  'transmition'     => array(
            'template'  => 'theme/transmition',
            'variables' => array(
                'items' => array(),
              ),
        ),
  'points_media'     => array(
            'template'  => 'theme/points_media',
            'variables' => array(
                'items' => array(),
              ),
        ),
  'half_rebounds'     => array(
            'template'  => 'theme/half_rebounds',
            'variables' => array(
                'items' => array(),
              ),
        ),
  'media_assistance'     => array(
            'template'  => 'theme/media_assistance',
            'variables' => array(
                'items' => array(),
              ),
        ),
  'sponsors_home'     => array(
            'template'  => 'theme/sponsors_home',
            'variables' => array(
                'items' => array(),
              ),
        ),
    );
}
/**
 * Functions custom by @edwindayscript
 */

/**
 * [_get_content_custom description]
 * @param  [type] $type     [description]
 * @param  [type] $quantity [description]
 * @return [type]           [description]
 */

function _get_content_custom($type, $quantity){
  $arraydatos = array();
  $query = db_select('node', 'n');
  $query->join('field_data_field_image', 'img', 'n.nid = img.entity_id');
  $query->join('field_data_body', 'b', 'n.nid = b.entity_id');
  $query->fields('n', array('title', 'nid'))
         ->fields('b', array('body_value'))
         ->fields('img', array('field_image_fid', 'field_image_alt', 'field_image_title'))
         ->condition('n.type', $type)
         ->range(0, $quantity)
         ->orderBy('n.created', 'DESC');
  $result = $query->execute();
  while ($row = $result->fetchAssoc()) {
    $arraydatos[] = array(
          "title" => $row["title"],
          "nid"   => drupal_get_path_alias('node/' . $row["nid"]),
          "body"  => substr($row["body_value"], 0 , 184),
          "fid"   =>  theme('image_style', array('style_name' => 'slidorion_home', 'path' => file_load($row["field_image_fid"])->uri, 'getsize' => FALSE, 'attributes' => array())),
          "fid_alt"=> $row["field_image_alt"],
          "fid_title"=> $row["field_image_title"],
        );
  }
  return $arraydatos;
}
/**
 * [getStandingData description]
 * @param  [type]  $sql  [description]
 * @param  boolean $load [description]
 * @return [type]        [description]
 */
function getStandingData(){
  $name= 'standing.json';
  $idQuery  =1;
  $query= baseSp . '/v1/basketball/competitions/' . liga . '/standings?latest=1&format=json&limit=50000&ak=' . ak . '';
  // if is old update
  $json = file_get_contents($query);
  $data = json_decode($json, TRUE);
  $fp = fopen(drupal_get_path('module', 'ligadtv') . '/data/'. $name,'w');
  fwrite($fp, json_encode($data));
  fclose($fp);
  $file= drupal_get_path('module', 'ligadtv') . "/data/" . $name;
  return json_decode(file_get_contents($file), true);
}
/**
 * [getStanding description]
 * @param  [type] $sql [description]
 * @return [type]      [description]
 */
function getStanding(){
  $data =  getStandingData();
  $data=$data['response']['data'];
  $dataTemp=$data;
  $size=count($data);
  /**
   * [$i description]
   * @var integer
   */
  for ($i=0; $i < $size; $i++) {
    $mayor['standingPoints']=-999;
    $pos=-1;
    for ($i2=0; $i2 < count($dataTemp); $i2++) {
      if($dataTemp[$i2]['standingPoints']>$mayor['standingPoints']){
        $mayor=$dataTemp[$i2];
        $pos=$i2;
      }
    }
    $data[$i]=$mayor;
    // print($dataTemp);
    unset($dataTemp[$pos]);
    $dataTemp = array_values($dataTemp);
  }
  return $data;
}
/**
 * [getCal description]
 * @return [type] [description]
 */
function getCal(){
  $data    = getCalData();
  $data    =$data['response']['data'];
  $dataTemp=$data;
  $size    =count($data);
  for ($i=0; $i < $size; $i++) {
    $mayor['matchNumber']=999;
    $pos                 =-1;
    for ($i2 = 0; $i2 < count($dataTemp); $i2++) {
      if($dataTemp[$i2]['matchNumber'] < $mayor['matchNumber']){
        $mayor=$dataTemp[$i2];
        $pos=$i2;
      }
    }
    $data[$i]=$mayor;
    unset($dataTemp[$pos]);
    $dataTemp = array_values($dataTemp);
  }
  return $data;
}
/**
 * [getCalData description]
 * @return [type] [description]
 */
function getCalData(){
  $name     = 'cal.json';
  $idQuery  = 2;
  $query    = baseSp . '/v1/basketball/competitions/' . liga . '/matches?format=json&limit=50000&ak=' . ak . '';
  $json     = file_get_contents($query);
  $data     = json_decode($json, TRUE);
  $fp       = fopen(drupal_get_path('module', 'ligadtv') . '/data/'.$name,'w');
  fwrite($fp, json_encode($data));
  fclose($fp);
  $file     = drupal_get_path('module', 'ligadtv') . '/data/' . $name;

  return json_decode(file_get_contents($file), true);
}
/**
 * [getRes description]
 * @param  [type] $sql [description]
 * @return [type]      [description]
 */
function getRes(){
  $data = getCalData();
  $data=$data['response']['data'];
  $dataTemp=$data;
  $size=count($data);
  for ($i=0; $i < $size; $i++) {
    $menor['matchNumber']=-1;
    $pos=-1;
    for ($i2=0; $i2 < count($dataTemp); $i2++) {
      if($dataTemp[$i2]['matchNumber']>$menor['matchNumber']){
        $menor=$dataTemp[$i2];
        $pos=$i2;
      }
    }
    $data[$i]=$menor;
    unset($dataTemp[$pos]);
    $dataTemp = array_values($dataTemp);
  }
  return $data;
}
/**
 * [transmition description]
 * @return [type] [description]
 */
function transmition(){
  $arraydatos = array();
  $query = db_select('node', 'n');
  $query->leftjoin('field_data_field_channel', 'ch', 'n.nid = ch.entity_id');
  $query->leftjoin('field_data_field_team_one', 't1', 'n.nid = t1.entity_id');
  $query->leftjoin('field_data_field_team_tow', 't2', 'n.nid = t2.entity_id');
  $query->leftjoin('field_data_field_date', 'd', 'n.nid = d.entity_id');
  $query->leftjoin('field_data_field_site', 's', 'n.nid = s.entity_id');
  $query->fields('n', array('title'))
        ->fields('t1', array('field_team_one_target_id'))
        ->fields('t2', array('field_team_tow_target_id'))
        ->fields('ch', array('field_channel_target_id'))
        ->fields('d', array('field_date_value'))
        ->fields('s', array('field_site_tid'))
        ->where('d.field_date_value > now()')
        ->condition('n.type', 'match')
        ->orderBy('n.created', 'DESC');
  $result = $query->execute();
  while ($row = $result->fetchAssoc()) {
    $arraydatos[] = array(
          "title"     => $row["title"],
          "channel"   => $row['field_channel_target_id'],
          "t1"        => $row["field_team_one_target_id"],
          "t2"        => $row["field_team_tow_target_id"],
          "date"      => $row["field_date_value"],
          "site"      => $row["field_site_tid"],
        );
  }
  return $arraydatos;
}
/**
 * [getLeaderPoints description]
 * @param  [type]  $sql  [description]
 * @param  boolean $load [description]
 * @return [type]        [description]
 */
function getLeaderPoints(){
  $name= 'sPointsAverage.json';
  $sLeaQuery = 'leaders/sPointsAverage';
  $query= baseSp . '/v1/basketball/competitions/' . liga . '/' . $sLeaQuery . '?format=json&ak=' . ak . '&limit=500';
  $json = file_get_contents($query);
  $data = json_decode( $json, TRUE);
  $fp = fopen(drupal_get_path('module', 'ligadtv') . '/data/'.$name,'w');
  fwrite($fp, json_encode($data));
  fclose($fp);
  $file=drupal_get_path('module', 'ligadtv') . '/data/' . $name;
  return json_decode(file_get_contents($file), true);
}
/**
 * [drawLeader description]
 * @param  [type] $data     [description]
 * @param  [type] $players  [description]
 * @param  [type] $teams    [description]
 * @param  string $info     [description]
 * @param  string $nameInfo [description]
 * @return [type]           [description]
 */
function drawLeader($data , $players, $teams, $info='sPoints', $nameInfo='MP'){
$data= $data['response'];
$stFinal='';
$cont = 0;
foreach ($data['data'] as $key => $value) {
    if($cont==6)break;
    $cont++;
    $person   = $players[$value['personId']];
    $name     = $value['firstName'].' '.$value['familyName'];
    $teamName = $value['teamName'];
    $points   = $value[$info];
    $image    = '';
    $team     = $teams[$person['primaryClubId']];
    $clubName = $team['clubName'];
    $clubName = substr($clubName, 0, 3);
    $name = substr($name, 0, 24);
    $escudo ='';
    if(isset($team['images']['logo']['T1']['url']))
      $escudo = $team['images']['logo']['T1']['url'];

    if(isset($value['images']['photo']['T1']))
        $image = $value['images']['photo']['T1']['url'];

    if($key==0){
        $header= <<<EOF
            <div class="dataPlayer">
                <div class="leaderImg">
                    <img src="{$image}">
                    <div class="titleLidder">Leader</div>
                </div>
                <div class="info">
                    <div class="inInfo">
                      <h4>{$name}</h4>
                      <h5>{$teamName}</h5>
                    </div>
                    <div class="cc1Info">
                        <div class="cc2Info">
                            {$points} {$nameInfo}
                        </div>
                        <img src="{$escudo}">
                    </div>
                </div>
            </div>
EOF;
        $returnData['header'] = $header;
    }
    else{
        $stFinal.='<tr>
                        <td >'.($key+1).'</td>
                        <td>'.$clubName.'</td>
                        <td>'.$name.'</td>
                        <td>'.$points.'</td>
                    </tr>';
    }
}
  $table = <<<EOF
<div class="tableLeader">
            <table>
                <thead>
                    <tr>
                        <td width="20px">#</td>
                        <td width="50px">EQU</td>
                        <td width="185px" style="text-align: left;">NOMBRE</td>
                        <td width="45px">{$nameInfo}</td>
                    </tr>
                </thead>
                <tbody>
                {$stFinal}
                </tbody>
            </table>
            <a href="/estadisticasTable?query={$info}&unit={$nameInfo}" class="verTodos">VER LISTA COMPLETA >></a>
        </div>
EOF;
  $returnData['table'] = $table;
  return $returnData;
}
/**
 * [getLeaderPointsRebotes description]
 * @param  [type]  $sql  [description]
 * @param  boolean $load [description]
 * @return [type]        [description]
 */
function getLeaderPointsRebotes(){
  $name= 'sReboundsTotalAverage.json';
  $idQuery  = 6;
  $sLeaQuery = 'leaders/sReboundsTotalAverage';
  $query= baseSp . '/v1/basketball/competitions/' . liga . '/' . $sLeaQuery . '?format=json&ak=' . ak . '&limit=500';
  $json = file_get_contents($query);
  $data = json_decode($json, TRUE);
  $fp = fopen(drupal_get_path('module', 'ligadtv') . '/data/' . $name,'w');
  fwrite($fp, json_encode($data));
  fclose($fp);
  $file=drupal_get_path('module', 'ligadtv') . '/data/' .$name;
  return json_decode(file_get_contents($file), true);
}
/**
 * [getLeaderMediaAsistencias2 description]
 * @param  [type]  $sql  [description]
 * @param  boolean $load [description]
 * @return [type]        [description]
 */
function getLeaderMediaAsistencias2($sql,$load=false){
  $name= 'sAssistsAverage.json';
  $sLeaQuery = 'leaders/sAssistsAverage';
  $query= baseSp . '/v1/basketball/competitions/' . liga . '/' . $sLeaQuery . '?format=json&ak=' . ak . '&limit=500';
  $json = file_get_contents($query);
  $data = json_decode($json, TRUE);
  $fp = fopen(drupal_get_path('module', 'ligadtv') . '/data/'.$name,'w');
    fwrite($fp, json_encode($data));
    fclose($fp);
  $file=drupal_get_path('module', 'ligadtv') . '/data/' . $name;
  return json_decode(file_get_contents($file), true);
}
?>
